### ISSUE TITLE
Tracking issue for 1.0 release

### ISSUE THREAD

**Issue by aochagavia** [aochagavia/rocket#63]
MVC:
- [x] Introduce view (https://github.com/aochagavia/rocket/pull/62)
- [x] Introduce controllers

Cleanup:
- [x] Use optimized version of `Vec::retain`
- [x] Split the `drawing` module in two: `Point` and `Size` should go to a `geometry` module, while `color` should remain in `drawing`.
- [x] Rename the `traits` module to `physics` or move its contents into the `geometry` module.
- [x] Run clippy (and maybe rustfmt) on the codebase
